"""
FastAPI backend for the containerized RAG assistant.

    uvicorn main:app --reload --port 8000     # needs Ollama on localhost:11434 for /ask

Swagger UI at http://localhost:8000/docs. The pipeline itself is in rag.py,
settings come from environment variables (config.py).
"""

import math
from typing import Literal

from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.encoders import jsonable_encoder
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

import rag
from config import settings

app = FastAPI(
    title="RAG API",
    version="1.0",
    description=(
        "Answers questions from the files in `docs/`. Call `POST /ingest` once, then `POST /ask`. "
        f"Answers are generated by {settings.model_name} through Ollama."
    ),
    debug=settings.debug,
)

# open to any origin, fine for a local coursework stack
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

NO_DOCUMENTS_ANSWER = "No documents have been ingested yet. Click Re-index Documents (POST /ingest) first."
NO_MATCH_ANSWER = (
    "I couldn't find anything in the documents close enough to this question to answer it. "
    "Try rephrasing it, or ask about Python, FastAPI, Streamlit, Docker or RAG."
)


# ── Request / Response schemas ─────────────────────────────────────────────

class AskRequest(BaseModel):
    # the embedding model only reads ~1000 characters, more wouldn't change the search
    question: str = Field(min_length=1, max_length=1000)
    # strict, otherwise pydantic turns true into 1 and "5" into 5
    n_results: int = Field(settings.max_results, ge=1, le=20, strict=True)
    max_distance: float = Field(settings.max_distance, ge=0, le=4, strict=True, allow_inf_nan=False)

    model_config = {"json_schema_extra": {"examples": [
        {"question": "What is a list comprehension?", "n_results": settings.max_results,
         "max_distance": settings.max_distance},
    ]}}

    # runs before min_length so "" and "   " get the same message
    @field_validator("question", mode="before")
    @classmethod
    def not_empty(cls, v):
        if isinstance(v, str):
            v = v.strip()
            # strip() leaves zero-width spaces, BOMs and control characters
            if not any(ch.isprintable() and not ch.isspace() for ch in v):
                raise ValueError("question must not be empty")
        return v


class SourceChunk(BaseModel):
    text: str
    source: str
    distance: float


class AskResponse(BaseModel):
    answer: str
    sources: list[SourceChunk]
    confidence: Literal["high", "medium", "low"]
    # why there are no sources, so clients don't have to parse the answer text
    status: Literal["answered", "no_documents", "no_match"]


class IngestResponse(BaseModel):
    chunks_ingested: int
    files_ingested: int
    chunks_removed: int
    message: str


class StatsResponse(BaseModel):
    document_count: int
    model: str
    db_path: str
    max_results: int
    confidence_threshold: float
    max_distance: float


class HealthResponse(BaseModel):
    status: Literal["ok", "degraded", "error"]
    chromadb: Literal["ok", "error"]
    ollama: Literal["connected", "disconnected"]
    document_count: int
    model: str
    model_pulled: bool


def error_doc(description: str, detail: str) -> dict:
    return {"description": description, "content": {"application/json": {"example": {"detail": detail}}}}


def chroma_unavailable(detail: str, cause: Exception) -> HTTPException:
    rag.log.warning("ChromaDB failed (%s): %r", detail, cause)
    return HTTPException(status_code=503, detail=detail)


# FastAPI's default 422 handler echoes the bad input back. NaN, Infinity and
# lone surrogates parse fine but can't be written out as JSON, so the error
# response itself used to blow up into a 500
def json_safe(value):
    if isinstance(value, float) and not math.isfinite(value):
        return str(value)
    if isinstance(value, str):
        return value.encode("utf-8", "replace").decode("utf-8")
    if isinstance(value, dict):
        return {k: json_safe(v) for k, v in value.items()}
    if isinstance(value, list | tuple):
        return [json_safe(v) for v in value]
    return value


@app.exception_handler(RequestValidationError)
async def validation_error(request: Request, exc: RequestValidationError):
    return JSONResponse(status_code=422, content={"detail": json_safe(jsonable_encoder(exc.errors()))})


# ── Endpoints ──────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {"message": "RAG API is running", "status": "ok", "docs": "/docs"}


@app.post(
    "/ask",
    response_model=AskResponse,
    responses={503: error_doc("Ollama is down, timed out, or doesn't have the model, or ChromaDB "
                              "can't be searched.", "Ollama unavailable")},
)
def ask(req: AskRequest):
    try:
        stored = rag.collection.count()
        chunks = rag.retrieve(req.question, req.n_results, req.max_distance) if stored else []
    except Exception as e:
        # the question gets embedded in here too, so a broken embedding model lands here as well
        raise chroma_unavailable("ChromaDB search failed", e) from e

    # no-context fallback: without chunks the model would only be guessing, so it isn't called
    if not stored:
        return AskResponse(answer=NO_DOCUMENTS_ANSWER, sources=[], confidence="low", status="no_documents")
    if not chunks:
        return AskResponse(answer=NO_MATCH_ANSWER, sources=[], confidence="low", status="no_match")

    answer = rag.generate(rag.build_prompt(req.question, chunks))
    return AskResponse(
        answer=answer,
        sources=[SourceChunk(**c) for c in chunks],
        confidence=rag.compute_confidence(chunks, answer),
        status="answered",
    )


@app.post(
    "/ingest",
    response_model=IngestResponse,
    responses={503: error_doc("ChromaDB couldn't be written to. Safe to call again.",
                              "Could not write to ChromaDB")},
)
def ingest():
    docs = rag.load_documents(rag.DOCS_DIR)
    if not docs:
        # an empty or missing folder is more likely a mistake than a request to wipe everything
        return IngestResponse(chunks_ingested=0, files_ingested=0, chunks_removed=0,
                              message="No .txt or .md content found in docs/, nothing changed")
    try:
        removed = rag.index_documents(docs)
    except Exception as e:
        raise chroma_unavailable("Could not write to ChromaDB", e) from e

    files = len({d["metadata"]["source"] for d in docs})
    message = f"Ingested {len(docs)} chunks from {files} files"
    if removed:
        message += f", removed {removed} stale chunks"
    return IngestResponse(chunks_ingested=len(docs), files_ingested=files, chunks_removed=removed, message=message)


@app.get(
    "/stats",
    response_model=StatsResponse,
    responses={503: error_doc("ChromaDB can't be read.", "ChromaDB is not readable")},
)
def stats():
    try:
        count = rag.collection.count()
    except Exception as e:
        raise chroma_unavailable("ChromaDB is not readable", e) from e
    return StatsResponse(
        document_count=count,
        model=settings.model_name,
        db_path=rag.DB_PATH,
        max_results=settings.max_results,
        confidence_threshold=settings.confidence_threshold,
        max_distance=settings.max_distance,
    )


@app.get("/health", response_model=HealthResponse, responses={503: {"description": "ChromaDB can't be read."}})
def health(response: Response):
    # ok: everything works. degraded: retrieval works but /ask can't generate
    # (Ollama down or model missing). error (503): ChromaDB is broken
    try:
        count, chroma_ok = rag.collection.count(), True
    # deliberately broad: whatever chroma raises has to show up as "error", not a 500
    except Exception as e:  # noqa: BLE001
        rag.log.warning("ChromaDB health check failed: %r", e)
        count, chroma_ok = 0, False

    ollama_ok, model_pulled = rag.ollama_status()

    if not chroma_ok:
        status = "error"
        response.status_code = 503
    elif ollama_ok and model_pulled:
        status = "ok"
    else:
        status = "degraded"

    return HealthResponse(
        status=status,
        chromadb="ok" if chroma_ok else "error",
        ollama="connected" if ollama_ok else "disconnected",
        document_count=count,
        model=settings.model_name,
        model_pulled=model_pulled,
    )
